apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: all-microservices-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      metrics: "true"
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
