apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  thanos.yaml: |-
    apiVersion: 1
    datasources:
    - name: Thanos
      type: prometheus
      url: http://thanos-query.monitoring.svc.cluster.local:9090
      access: proxy
      isDefault: false
