objstoreConfig: "thanos-objstore-config"
querier:
  enabled: true
  stores:
    - "prometheus-kube-prometheus-thanos-discovery.monitoring.svc.cluster.local:10901"
storegateway:
  enabled: true
compactor:
  enabled: true
  retentionResolutionRaw: 30d
  retentionResolution5m: 30d
  retentionResolution1h: 30d
